# for local development
version: "3.7"

networks:
  ifc-dw2-vulnerabilidades-network:
    external: true

volumes:
  ifc-dw2-vulnerabilidades-db:
    external: true

services:
  db:
    container_name: ifc-dw2-vulnerabilidades-db
    image: "postgres:14-alpine"
    restart: always
    volumes:
      - ifc-dw2-vulnerabilidades-db:/var/lib/postgresql/data
    env_file:
      - .env.local
      - .env.${NODE_ENV}.local
      - .env.${NODE_ENV}
      - .env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5432:5432
    networks:
      - ifc-dw2-vulnerabilidades-network
  app:
    container_name: nest-vite
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
      - 3001:3001
    stdin_open: true
    tty: true
    volumes:
      - ".:/srv/www"
      - /srv/www/node_modules/
    networks:
      - ifc-dw2-vulnerabilidades-network
    command: sh -c "cd config && node run.mjs"'
    env_file:
      - .env.local
      - .env.${NODE_ENV}.local
      - .env.${NODE_ENV}
      - .env
